// company-manager-react/src/pages/departments/department-detail/DepartmentDetail.js
import React, {useEffect, useState} from 'react';
import {NavLink, useNavigate, useParams} from "react-router-dom";
import useHttp from "../../../hooks/use-http";
import {BASE_URL} from "../../../config/AppConfig";

export function DepartmentDetail() {
    const params = useParams();
    const navigate = useNavigate();

    const editMode = params.id !== 'create';
    const header = 'Department Detail';

    const [formData, setFormData] = useState({name: "", location: ""});
    const [department, setDepartment] = useState(undefined);
    const [modify, setModify] = useState(undefined);
    const {error: departmentError, sendRequest: departmentApi} = useHttp();

    useEffect(() => {
        if (editMode) {
            const applyDepartment = (data) => {
                setDepartment(data);
                setFormData(data);
            }
            departmentApi({url: `${BASE_URL}/departments/${params.id}`}, applyDepartment)
        }
    }, []);
    useEffect(() => {
        if (modify?.event === 'delete') {
            const afterDelete = () => navigate('/departments');
            departmentApi({
                url: `${BASE_URL}/departments/${params.id}`,
                method: 'DELETE'
            }, afterDelete);
        }
    }, [modify]);
    useEffect(() => {
        if (modify?.event === 'save') {
            if (editMode) {
                departmentApi({
                    url: `${BASE_URL}/departments/${params.id}`,
                    method: 'PUT',
                    headers: {'Content-Type': 'application/json'},
                    body: formData
                }, () => {
                    navigate('/departments')
                });
            } else {
                departmentApi({
                    url: `${BASE_URL}/departments`,
                    method: 'POST',
                    headers: {'Content-Type': 'application/json'},
                    body: formData
                }, () => {
                    navigate('/departments')
                });
            }
        }
    }, [modify]);

    const inputChangeHandler = (event) => {
        const {id, value} = event.target;
        setFormData({...formData, [id]: value})
    }
    const onSubmitHandler = (event) => {
        event.preventDefault();
        setModify({event: 'save'});
    }
    const onDeleteHandler = () => setModify({event: 'delete'});
    const disabled = () => Object.keys(formData).some(key => formData[key] === null || formData[key] === "");

    return (
        <div className="container-fluid">
            <div className="row my-2">
                <div className="col-sm-12 col-md-9 d-md-inline-flex">
                    <h3 className="me-md-auto">{header}
                        {editMode && <React.Fragment>
                            <span> for</span>
                            <span className="highlight-blue"> {department?.name}</span>
                        </React.Fragment>}
                    </h3>
                    <button className="btn btn-sm btn-danger" style={{height: 'fit-content'}}
                            onClick={onDeleteHandler}>
                        <i className="bi bi-trash me-1"></i>Delete
                    </button>
                </div>
            </div>

            <form onSubmit={onSubmitHandler}>
                <div className="form-group row mt-2 align-items-center">
                    <label htmlFor="name" className="col-md-3 col-sm-12">Name *</label>
                    <div className="col-md-6 col-sm-12">
                        <input id="name" type="text" className="form-control"
                               defaultValue={formData?.name}
                               onChange={(e) => inputChangeHandler(e)}/>
                    </div>
                </div>
                <div className="form-group row mt-2 align-items-center">
                    <label htmlFor="location" className="col-md-3 col-sm-12">Location *</label>
                    <div className="col-md-6 col-sm-12">
                        <input id="location" type="text" className="form-control"
                               defaultValue={formData?.location}
                               onChange={(e) => inputChangeHandler(e)}/>
                    </div>
                </div>


                <div className="row mt-3">
                    <div className="col-md-9 col-sm-12 text-end">
                        <NavLink to={'/departments'}>
                            <button type="button" className="btn btn-sm btn-secondary me-2">Cancel</button>
                        </NavLink>
                        <button type="submit" disabled={disabled()} className="btn btn-sm btn-success">Save</button>
                    </div>
                </div>
            </form>
        </div>
    )


}

export default DepartmentDetail;

// company-manager-angular/src/app/content/departments/department-detail/department-detail.component.ts
import {Component, OnDestroy, OnInit} from '@angular/core';
import {BaseApi} from "../../../services/api/base.api";
import {Department} from "../../../services/model/department.model";
import {Location} from "@angular/common";
import {ActivatedRoute} from "@angular/router";
import {FormControl, FormGroup, Validators} from "@angular/forms";
import {Subscription} from "rxjs";

@Component({
  selector: 'app-department-detail',
  templateUrl: './department-detail.component.html',
  styleUrls: ['./department-detail.component.scss']
})
export class DepartmentDetailComponent implements OnInit, OnDestroy {

  public formGroup!: FormGroup;
  public subscription!: Subscription;
  public departmentId!: number;

  public department!: Department;
  public fields: { key: string, label: string, required: boolean, type: string | null }[] = [
    {key: 'name', label: 'Name', required: true, type: 'text'},
    {key: 'location', label: 'Location', required: true, type: 'text'}
  ];

  constructor(private departmentApi: BaseApi<Department>,
              private location: Location,
              private route: ActivatedRoute) {

  }

  ngOnInit() {
    this.subscription = this.route.paramMap.subscribe(params => {
      this.departmentId = Number(params.get('id')) || NaN;

      if (!isNaN(this.departmentId)) {
        this.getDepartmentDetails(this.departmentId);
      }
    });

    this.formGroup = new FormGroup({});
    this.fields.forEach(field => {
      const control = new FormControl(null);
      if (field.required) {
        control.addValidators(Validators.required);
      }
      this.formGroup.addControl(field.key, control);
    });
  }

  ngOnDestroy() {
    this.subscription?.unsubscribe();
  }

  private getDepartmentDetails(departmentId: number): void {
    this.departmentApi.get('/departments/'.concat(String(departmentId))).then(result => {
      this.department = result as Department;
      this.formGroup.patchValue(this.department);
    });
  }

  public navBack(): void {
    this.location.back();
  }

  public onDelete(): void {
    this.departmentApi.delete(`/departments/${this.departmentId}`).then(() => this.navBack());
  }

  public onSave(): void {
    const body = this.formGroup.getRawValue();

    if (!isNaN(this.departmentId)) {
      this.departmentApi.put(`/departments/${this.departmentId}`, body).then(() => this.navBack());
    } else {
      this.departmentApi.post(`/departments`, body).then(() => this.navBack());
    }
  }
}

<div class="container-fluid" *ngIf="this.formGroup">
  <div class="row my-2">
    <div class="col-sm-12 col-md-9 d-md-inline-flex">
      <h3 class="me-md-auto">Department Detail
        <ng-container *ngIf="this.department">for
          <span class="highlight-blue"> {{this.department.name}}</span>
        </ng-container>
      </h3>
      <button type="button" class="btn btn-sm btn-danger" [style]="{height: 'fit-content'}"
              (click)="this.onDelete()"
              *ngIf="this.departmentId">
        <i class="bi bi-trash me-1"></i>Delete
      </button>
    </div>

  </div>
  <form [formGroup]="this.formGroup">
    <div class="form-group row mt-2 align-items-center" *ngFor="let field of this.fields">
      <label [for]="'id_' + field.key" class="col-md-3 col-sm-12">
        {{field.label}}
        <ng-container *ngIf="field.required">*</ng-container>
      </label>
      <div class="col-md-6 col-sm-12">
        <input [id]="'id_' + field.key" [type]="field.type" class="form-control"
               [formControlName]="field.key" [placeholder]="field.label"/>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-9 col-sm-12 text-end">
        <button type="button" class="btn btn-sm btn-secondary me-2" (click)="this.navBack()">Cancel</button>
        <button type="submit" class="btn btn-sm btn-success" [disabled]="this.formGroup.invalid"
                (click)="this.onSave()">Save
        </button>
      </div>
    </div>
  </form>
</div>
