// company-manager-angular/src/app/content/employees/employee-card/employee-card.component.ts
import {Component, Input} from '@angular/core';
import {Employee} from "../../../services/model/employee.model";
import {Router} from "@angular/router";

@Component({
  selector: 'app-employee-card',
  templateUrl: './employee-card.component.html',
  styleUrls: ['./employee-card.component.scss']
})
export class EmployeeCardComponent {
  @Input()
  public employee!: Employee;

  constructor(private router: Router) {

  }

  public navToDetail(employeeId?: number): void {
    this.router.navigate(['employees/'.concat(employeeId ? String(employeeId) : 'new')]);
  }

}

<div class="card company-card" (click)="this.navToDetail(employee.id)">
  <div class="card-body">
    <div class="d-inline-flex w-100">
      <h5 class="card-title me-auto">{{employee.lastname}}</h5>
      <span class="badge text-bg-primary dept-badge" *ngIf="employee.department; else noDepartment">
              {{employee.department.name}}
            </span>
      <ng-template #noDepartment>
        <span class="badge text-bg-danger dept-badge">no department</span>
      </ng-template>
    </div>

    <h6 class="card-subtitle mb-2 text-muted">{{employee.job}}</h6>
    <div class="card-text">
      <div class="row">
        <div class="col-6">
          <i class="bi bi-calendar me-2"></i>{{employee.hireDate | date: 'dd.MM.yyyy'}}
        </div>
        <div class="col-6 text-end">
          <i class="bi bi-cash me-2"></i>
          <span>{{employee.salary | number: '.2'}} €</span>
        </div>
      </div>
      <div class="row">
        <div class="col-6">
          <i class="bi bi-person me-2"></i>{{employee.manager?.lastname || '-'}}
        </div>
        <div class="col-6 text-end" *ngIf="employee.commission">
          <i class="bi bi-piggy-bank-fill me-2"></i>
          <span>{{employee.commission | number: '.2'}} €</span>
        </div>
      </div>
    </div>
  </div>
</div>

// company-manager-react/src/pages/employees/employee-card/EmployeeCard.js
import classes from "../Employees.module.css";
import dayjs from "dayjs";
import React from "react";
import {useNavigate} from "react-router-dom";

export function EmployeeCard({props}) {
    const navigate = useNavigate();


    return <div className="card company-card" onClick={() => navigate(`${props.id}`)}>
        <div className="card-body">
            <div className="d-inline-flex w-100">
                <h5 className="card-title me-auto">{props?.lastname}</h5>
                {props?.department && <span
                    className={`badge text-bg-primary ${classes['dept-badge']}`}>{props.department.name}</span>}
                {!props?.department && <span
                    className={`badge text-bg-danger ${classes['dept-badge']}`}>no department</span>}
            </div>

            <h6 className="card-subtitle mb-2 text-muted">{props?.job}</h6>
            <div className="card-text">
                <div className="row">
                    <div className="col-6">
                        <i className="bi bi-calendar me-2"></i>{dayjs(props.hireDate).format('DD.MM.YYYY')}
                    </div>

                    <div className="col-6 text-end">
                        <i className="bi bi-cash me-2"></i>
                        <span>{props.salary?.toFixed(2)} €</span>
                    </div>
                </div>

                <div className="row">
                    <div className="col-6 ">
                        <i className="bi bi-person me-2"></i>{props.manager?.lastname || '-'}
                    </div>
                    {props.commission > 0 && <div className="col-6 text-end">
                        <i className="bi bi-piggy-bank-fill me-2"></i>
                        <span>{props.commission?.toFixed(2)} €</span>
                    </div>}
                </div>
            </div>
        </div>
    </div>
}
