// company-manager-angular/src/app/content/employees/employee-detail/employee-detail.component.ts
import {Component, OnDestroy, OnInit} from '@angular/core';
import {BaseApi} from "../../../services/api/base.api";
import {Employee} from "../../../services/model/employee.model";
import {FormControl, FormGroup, Validators} from "@angular/forms";
import {ActivatedRoute, Router} from "@angular/router";
import {Subscription} from "rxjs";
import {Pagination} from "../../../services/model/pagination.model";
import {Department} from "../../../services/model/department.model";
import {Location} from "@angular/common";

@Component({
  selector: 'app-employee-detail',
  templateUrl: './employee-detail.component.html',
  styleUrls: ['./employee-detail.component.scss']
})
export class EmployeeDetailComponent implements OnInit, OnDestroy {
  public formGroup!: FormGroup;
  public subscription!: Subscription;
  public employeeId!: number;

  public employee!: Employee;
  public managers!: Employee[];
  public departments!: Department[];

  public fields: { key: string, label: string, required: boolean, default: any, type: string | null }[] = [
    {key: 'lastname', label: 'Lastname', required: true, default: '', type: 'text'},
    {key: 'job', label: 'Job', required: true, default: '', type: 'text'},
    {key: 'manager', label: 'Manager', required: true, default: null, type: null},
    {key: 'hireDate', label: 'Hiredate', required: true, default: '', type: 'date'},
    {key: 'salary', label: 'Salary', required: true, default: 0, type: 'number'},
    {key: 'commission', label: 'Commission', required: false, default: null, type: 'number'},
    {key: 'department', label: 'Department', required: true, default: null, type: null},
  ];

  constructor(private employeeApi: BaseApi<Employee>,
              private departmentApi: BaseApi<Department>,
              private location: Location,
              private route: ActivatedRoute) {
  }

  ngOnInit() {
    this.subscription = this.route.paramMap.subscribe(params => {
      this.employeeId = Number(params.get('id')) || NaN;

      if (!isNaN(this.employeeId)) {
        this.getEmployeeDetails(this.employeeId);
      }
    });

    this.getManagers();
    this.getDepartments();

    this.formGroup = new FormGroup({});
    this.fields.forEach(field => {
      const control = new FormControl(field.default);
      if (field.required) {
        control.addValidators(Validators.required);
      }
      this.formGroup.addControl(field.key, control);
    });
  }

  ngOnDestroy() {
    this.subscription.unsubscribe();
  }

  private getEmployeeDetails(employeeId: number): void {
    this.employeeApi.get('/employees/'.concat(String(employeeId))).then(result => {
      this.employee = result;
      this.formGroup.patchValue({
        ...this.employee,
        department: this.employee.department?.id || null,
        manager: this.employee.manager?.id || null,
        hireDate: this.employee.hireDate?.split('T')[0]
      });
    });
  }

  private getManagers(): void {
    this.employeeApi.getAll('/employees', {
      'page': '0',
      'size': '50000'
    }).then(result => this.managers = (result as Pagination<Employee>).items);
  }

  private getDepartments(): void {
    this.departmentApi.getAll('/departments', {
      'page': '0',
      'size': '50000'
    }).then(result => this.departments = (result as Pagination<Department>).items);
  }

  public navBack(): void {
    this.location.back();
  }

  public onSave(): void {
    const body = this.formGroup.getRawValue();

    body.departmentId = body.department;
    body.managerId = body.manager;
    body.hireDate = new Date(body.hireDate).toISOString();

    delete body.manager;
    delete body.department;

    if (!isNaN(this.employeeId)) {
      this.employeeApi.put(`/employees/${this.employeeId}`, body).then(() => this.navBack());
    } else {
      this.employeeApi.post(`/employees`, body).then(() => this.navBack());
    }
  }

  public onDelete(): void {
    this.employeeApi.delete(`/employees/${this.employeeId}`).then(() => this.navBack());
  }
}

<div class="container-fluid" *ngIf="this.formGroup">
  <div class="row my-2">
    <div class="col-sm-12 col-md-9 d-md-inline-flex">
      <h3 class="me-md-auto">Employee Detail
        <ng-container *ngIf="this.employee">for
          <span class="highlight-blue"> {{this.employee.lastname}}</span>
        </ng-container>
      </h3>
      <button type="button" class="btn btn-sm btn-danger" [style]="{height: 'fit-content'}"
              (click)="this.onDelete()"
              *ngIf="this.employeeId">
        <i class="bi bi-trash me-1"></i>Delete
      </button>
    </div>
  </div>
  <form [formGroup]="this.formGroup">
    <div class="form-group row mt-2 align-items-center" *ngFor="let field of this.fields">
      <label [for]="'id_' + field.key" class="col-md-3 col-sm-12">
        {{field.label}}
        <ng-container *ngIf="field.required">*</ng-container>
      </label>
      <div class="col-md-6 col-sm-12">
        <ng-container [ngSwitch]="field.key">
          <ng-container *ngSwitchCase="'manager'">
            <select [id]="'id_' + field.key" [formControlName]="field.key" class="form-control">
              <option [ngValue]="null" [selected]="true">Please select ...</option>
              <option *ngFor="let manager of this.managers" [ngValue]="manager.id">{{manager.lastname}} ({{manager.job}})</option>
            </select>
          </ng-container>
          <ng-container *ngSwitchCase="'department'">
            <select [id]="'id_' + field.key" [formControlName]="field.key" class="form-control">
              <option [ngValue]="null" [selected]="true">Please select ...</option>
              <option *ngFor="let department of this.departments" [ngValue]="department.id">{{department.name}}</option>
            </select>
          </ng-container>

          <input *ngSwitchDefault [id]="'id_' + field.key" [type]="field.type" class="form-control"
                 [formControlName]="field.key" [placeholder]="field.label"/>
        </ng-container>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-9 col-sm-12 text-end">
        <button type="button" class="btn btn-sm btn-secondary me-2" (click)="this.navBack()">Cancel</button>
        <button type="submit" class="btn btn-sm btn-success" [disabled]="this.formGroup.invalid"
                (click)="this.onSave()">Save
        </button>
      </div>
    </div>
  </form>
</div>

// company-manager-react/src/pages/employees/employee-detail/EmployeeDetail.js
import React, {useEffect, useState} from 'react';
import {NavLink, useNavigate, useParams} from "react-router-dom";
import useHttp from "../../../hooks/use-http";
import {BASE_URL} from "../../../config/AppConfig";

export function EmployeeDetail() {
    const params = useParams();
    const navigate = useNavigate();

    const editMode = params.id !== 'create';
    const header = 'Employee Detail';

    const [formData, setFormData] = useState({
        lastname: "",
        job: "",
        manager: null,
        hireDate: "",
        salary: 0,
        commission: null,
        department: null
    });
    const [employee, setEmployee] = useState(undefined);
    const [departments, setDepartments] = useState([]);
    const [managers, setManagers] = useState([]);
    const [modify, setModify] = useState(undefined);
    const {error: employeeError, sendRequest: employeeApi} = useHttp();
    const {error: departmentError, sendRequest: departmentApi} = useHttp();

    useEffect(() => {
        if (editMode) {
            const applyEmployee = (data) => {
                setEmployee(data);
                setFormData({...data, hireDate: data.hireDate?.split('T')[0]});
            }
            employeeApi({url: `${BASE_URL}/employees/${params.id}`}, applyEmployee)
        }
    }, []);
    useEffect(() => {
        if (modify?.event === 'delete') {
            const afterDelete = () => navigate('/employees');
            employeeApi({
                url: `${BASE_URL}/employees/${params.id}`,
                method: 'DELETE'
            }, afterDelete);
        }
    }, [modify]);
    useEffect(() => {
        if (modify?.event === 'save') {
            const body = {
                ...formData,
                hireDate: new Date(formData.hireDate).toISOString(),
                managerId: formData.manager,
                departmentId: formData.department
            };
            delete body.manager;
            delete body.department;

            if (editMode) {
                employeeApi({
                    url: `${BASE_URL}/employees/${params.id}`,
                    method: 'PUT',
                    headers: {'Content-Type': 'application/json'},
                    body: body
                }, () => {
                    navigate('/employees')
                });
            } else {
                employeeApi({
                    url: `${BASE_URL}/employees`,
                    method: 'POST',
                    headers: {'Content-Type': 'application/json'},
                    body: body
                }, () => {
                    navigate('/employees')
                });
            }
        }
    }, [modify]);
    useEffect(() => {
        const applyDepartments = (data) => {
            setDepartments(data);
        }
        departmentApi({url: `${BASE_URL}/departments`}, applyDepartments)
    }, [editMode]);
    useEffect(() => {
        const applyManagers = (data) => setManagers(data);
        employeeApi({url: `${BASE_URL}/employees`}, applyManagers)
    }, [editMode])

    const inputChangeHandler = (event) => {
        const {id, value} = event.target;
        setFormData({...formData, [id]: value})
    }
    const onSubmitHandler = (event) => {
        event.preventDefault();
        setModify({event: 'save'});
    }
    const onDeleteHandler = () => setModify({event: 'delete'});

    const disabled = () => Object.keys(formData).filter(key => key !== 'commission').some(key => formData[key] === null || formData[key] === "");

    return (
        <div className="container-fluid">
            <div className="row my-2">
                <div className="col-sm-12 col-md-9 d-md-inline-flex">
                    <h3 className="me-md-auto">{header}
                        {editMode && <React.Fragment>
                            <span> for</span>
                            <span className="highlight-blue"> {employee?.lastname}</span>
                        </React.Fragment>}
                    </h3>
                    <button className="btn btn-sm btn-danger" style={{height: 'fit-content'}}
                            onClick={onDeleteHandler}>
                        <i className="bi bi-trash me-1"></i>Delete
                    </button>
                </div>
            </div>

            <form onSubmit={onSubmitHandler}>
                <div className="form-group row mt-2 align-items-center">
                    <label htmlFor="lastname" className="col-md-3 col-sm-12">Lastname *</label>
                    <div className="col-md-6 col-sm-12">
                        <input id="lastname" type="text" className="form-control" placeholder={'Lastname'}
                               defaultValue={formData?.lastname}
                               onChange={(e) => inputChangeHandler(e)}/>
                    </div>
                </div>
                <div className="form-group row mt-2 align-items-center">
                    <label htmlFor="job" className="col-md-3 col-sm-12">Job *</label>
                    <div className="col-md-6 col-sm-12">
                        <input id="job" type="text" className="form-control" placeholder={'Job'}
                               defaultValue={formData?.job}
                               onChange={(e) => inputChangeHandler(e)}/>
                    </div>
                </div>

                <div className="form-group row mt-2 align-items-center">
                    <label htmlFor="manager" className="col-md-3 col-sm-12">Manager *</label>
                    <div className="col-md-6 col-sm-12">

                        <select id='manager' className={'form-control'} value={formData.manager?.id} onChange={(e) => inputChangeHandler(e)}>
                            {managers?.map(manager => <option key={manager.id}
                                                              defaultValue={manager.id}>{manager.lastname} ({manager.job})</option>)}
                            <option key={'unselected:mgr'} value={null}>Please select...</option>
                        </select>
                    </div>
                </div>

                <div className="form-group row mt-2 align-items-center">
                    <label htmlFor="hireDate" className="col-md-3 col-sm-12">Hiredate *</label>
                    <div className="col-md-6 col-sm-12">
                        <input id="hireDate" type="date" className="form-control" placeholder={'Hiredate'}
                               defaultValue={formData?.hireDate}
                               onChange={(e) => inputChangeHandler(e)}/>
                    </div>
                </div>

                <div className="form-group row mt-2 align-items-center">
                    <label htmlFor="salary" className="col-md-3 col-sm-12">Salary *</label>
                    <div className="col-md-6 col-sm-12">
                        <input id="salary" type="number" className="form-control" placeholder={'Salary'}
                               defaultValue={formData?.salary}
                               onChange={(e) => inputChangeHandler(e)}/>
                    </div>
                </div>

                <div className="form-group row mt-2 align-items-center">
                    <label htmlFor="commission" className="col-md-3 col-sm-12">Commission</label>
                    <div className="col-md-6 col-sm-12">
                        <input id="commission" type="number" className="form-control" placeholder={'Commission'}
                               defaultValue={formData?.commission}
                               onChange={(e) => inputChangeHandler(e)}/>
                    </div>
                </div>

                <div className="form-group row mt-2 align-items-center">
                    <label htmlFor="department" className="col-md-3 col-sm-12">Department *</label>
                    <div className="col-md-6 col-sm-12">

                        <select id='department' className={'form-control'} value={formData.department?.id} onChange={(e) => inputChangeHandler(e)}>
                            {departments?.map(dept => <option key={dept.id}
                                                              defaultValue={dept.id}>{dept.name}</option>)}
                            <option key={'unselected_dept'} value={null}>Please select...</option>
                        </select>
                    </div>
                </div>


                <div className="row mt-3">
                    <div className="col-md-9 col-sm-12 text-end">
                        <NavLink to={'/employees'}>
                            <button type="button" className="btn btn-sm btn-secondary me-2">Cancel</button>
                        </NavLink>
                        <button type="submit" disabled={disabled()} className="btn btn-sm btn-success">Save</button>
                    </div>
                </div>
            </form>
        </div>

    )


}

export default EmployeeDetail;
