// company-manager-react/src/layout/header/Header.js
import {NavLink} from "react-router-dom";

function Header() {
    return (
        <header>
            <nav className="navbar navbar-expand-lg navbar-dark bg-dark shadow-sm">
                <div className="container-fluid">
                    <a className="navbar-brand me-3">
                        <i className="bi bi-buildings-fill me-1"></i>
                        Company Manager</a>
                    <button className="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false"
                            aria-label="Toggle navigation">
                        <span className="navbar-toggler-icon"></span>
                    </button>
                    <div className="collapse navbar-collapse" id="navbarText">
                        <ul className="navbar-nav me-auto mb-2 mb-lg-0">
                            <li className="nav-item">
                                <NavLink className="nav-link ms-lg-2" aria-current="page"
                                         to='/departments'>Departments</NavLink>
                            </li>
                            <li className="nav-item">
                                <NavLink className="nav-link ms-lg-2" aria-current="page"
                                         to='/employees'>Employees</NavLink>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
    );
}

export default Header;

// company-manager-angular/src/app/frame/header/header.component.ts
import {Component, OnDestroy} from '@angular/core';
import {NavigationEnd, Router, RouterEvent} from "@angular/router";
import {filter, Subscription} from "rxjs";

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnDestroy {
  public routes: { link: string, desc: string }[] = [
    {link: '/departments', desc: 'Departments'},
    {link: '/employees', desc: 'Employees'},
  ];
  public active!: string;
  public routerSub!: Subscription;

  constructor(private router: Router) {
    this.routerSub = router.events
      .pipe(filter(event => event instanceof NavigationEnd))
      .subscribe(data => {
        const url = (data as RouterEvent).url;
        this.active = '/'.concat(url?.split('/')[1] || 'employees');
      });
  }

  ngOnDestroy() {
    this.routerSub?.unsubscribe();
  }
}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand me-3">
      <i class="bi bi-buildings-fill me-1"></i>Company Manager
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item" *ngFor="let route of this.routes">
          <a class="nav-link" [routerLink]="route.link"
             (click)="this.active = route.link"
             [ngClass]="{'active': active === route.link}">{{route.desc}}</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
